# Site settings
title: Between Code and Math
author:
  name: Prasanna Maddila
description: "Personal blog on things I find interesting about code and math."
url: https://prasannamaddila.github.io/

# Build settings
remote_theme: jekyll/minima@3cdd14d
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Get the dark mode
minima:
    skin: dark

# Build settings
markdown: kramdown

header_pages:
    - about.md
    - news.md
